-- =============================================================================
-- Pivot Cloud — Étape 31 : vraies traductions françaises des 56 exercices
-- partagés (le texte français d'origine, avant leur traduction en
-- anglais à l'étape 15) -- pour tester le sélecteur de langue avec de
-- vraies données, comme demandé par Daniel.
-- =============================================================================
-- Run in Supabase: SQL Editor → New query → paste → Run.
-- Requiere haber aplicado antes step17 (idioma en exercises).
--
-- categories/material/age NE sont PAS traduits ici : ce sont des
-- étiquettes de filtre communes à toute l'app (le même vocabulaire
-- anglais, quel que soit l'idioma du texte) -- seuls le nom, les
-- objectifs, la description et les variantes changent de langue. On les
-- récupère depuis la ligne anglaise existante (repérée par son numéro),
-- avec exactement son translation_group_id, pour qu'elles soient
-- reconnues comme "la même jugada, en français".
-- =============================================================================

do $$
declare
  fr record;
  en_row record;
begin
  for fr in
    select * from (values
  (1, 'Bonjour', ARRAY['Tête levée','Présentation'], ARRAY['Dribbler sans regarder','Garder la tête levée'], 'Chaque joueur se déplace librement en dribblant dans un espace délimité. À chaque fois que deux joueurs se croisent, ils se saluent en disant Bonjour, se serrent la main et se présentent en donnant leur prénom, tout en continuant à contrôler leur ballon. L''objectif est d''encourager les joueurs à garder la tête levée, à observer leur environnement et à contrôler leur dribble sans regarder le ballon.', 'Saluer main gauche/droite ; Pierre-Feuille-Ciseaux ; s''asseoir en dribblant ; toucher le pied ; changer de main ; dire son pays ; toucher la ligne de fond.'),
  (2, 'Automates', ARRAY['Imitation','Créativité'], ARRAY['Garder la tête levée','Dribbler sans regarder','Découvrir différentes façons de dribbler'], 'Chaque joueur se déplace librement dans la salle avec un ballon. Les joueurs reproduisent exactement les actions de l''entraîneur. Celui-ci propose différentes façons de dribbler : main droite, main gauche, doigt, coude, assis, dribbles hauts, dribbles bas. Les joueurs doivent toujours regarder l''entraîneur afin de dribbler sans regarder leur ballon.', 'Statique ou en déplacement ; toucher une ligne ; ajouter des sauts ; utiliser différentes parties du corps ; laisser un joueur inventer un dribble.'),
  (3, 'Train et wagons', ARRAY['Observation','Adaptation'], ARRAY['Dribbler sans regarder','Garder la tête levée','S''adapter à la locomotive'], 'La classe est divisée en trois ou quatre trains, selon le nombre de joueurs. L''idéal est de former des groupes de quatre ou cinq joueurs. Le premier joueur est la locomotive et les autres sont les wagons. La locomotive choisit librement la manière de dribbler : main droite, main gauche, changements de main, dribble haut, dribble bas, assis ou toute autre variante, sans effectuer de tir. Tous les wagons reproduisent les actions de la locomotive en restant en mouvement. Au signal de l''entraîneur, le dernier wagon devient la nouvelle locomotive et invente de nouvelles actions.', 'Utiliser certaines lignes du terrain ; limiter la zone de jeu ; ajouter des changements de direction ; terminer le parcours par un tir ; laisser chaque nouvelle locomotive inventer une nouvelle façon de dribbler.'),
  (4, 'Loup glacé', ARRAY['Poursuite','Vitesse'], ARRAY['Dribbler tête levée','Observer autour','Dribbler vite'], 'Tous les joueurs ont un ballon et évoluent dans une zone délimitée par des cônes. Deux ou trois joueurs sont désignés comme loups. Les loups doivent toucher les moutons, tandis que les moutons doivent garder la tête levée, dribbler et s''éloigner des loups sans sortir de la zone. Lorsqu''un mouton est touché, il reste immobile jusqu''à ce qu''un autre joueur le libère en passant entre ses jambes tout en gardant le contrôle de son ballon.', 'Loup hôpital avec tapis ; imposer le dribble avec la main faible ; augmenter ou diminuer le nombre de loups ; réduire ou agrandir la zone de jeu.'),
  (5, 'Les voitures', ARRAY['Arrêts','Circulation'], ARRAY['Arrêt 1 temps','Arrêt 2 temps','Croiser des deux côtés','Dribbler tête levée'], 'Tous les joueurs ont un ballon et se déplacent en dribblant uniquement sur les lignes du terrain, comme des voitures circulant sur des routes. À chaque approche d''un croisement, l''entraîneur annonce une consigne : arrêt en un temps, arrêt en deux temps, ou passage par la droite ou par la gauche. Les joueurs doivent respecter la consigne tout en gardant la tête levée afin d''observer les autres, éviter les collisions et repartir au bon moment sans perdre le contrôle de leur ballon.', 'Les joueurs choisissent eux-mêmes de quel côté se croiser ; utiliser des cônes de différentes couleurs comme des feux de circulation ; imposer le dribble avec la main faible.'),
  (6, 'Carnaval des animaux', ARRAY['Créativité','Coordination'], ARRAY['Dribbles variés','Tête levée'], 'Chaque joueur dribble librement avec un ballon. L''entraîneur annonce un animal et les joueurs imitent sa manière de se déplacer tout en dribblant. Après quelques exemples, certains enfants proposent à leur tour de nouveaux animaux que tout le groupe reproduit. L''objectif est d''adapter le dribble à différentes situations tout en gardant la tête levée.', 'Imposer le dribble avec une seule main ; ajouter une règle à chaque nouvel animal ; varier la vitesse des déplacements.'),
  (7, 'Chasseur et lièvres', ARRAY['Lecture','Traversée'], ARRAY['Tête levée','Dribbler sans regarder','Dribbler vite','Lecture du jeu'], 'Un joueur est désigné comme chasseur et se place sur la ligne centrale. Il peut uniquement se déplacer le long de cette ligne et ne possède pas de ballon. Tous les autres joueurs, les lièvres, commencent sur une ligne de fond avec un ballon. Au signal, ils traversent le terrain en dribblant jusqu''à la ligne de fond opposée, sans jamais arrêter leur dribble ni sortir des limites du terrain. Pendant leur traversée, le chasseur tente de les toucher. Tout lièvre touché devient immédiatement chasseur, laisse son ballon sur le côté et rejoint la ligne centrale pour aider à toucher les autres joueurs lors des traversées suivantes. Le dernier lièvre restant remporte la partie.', 'Les chasseurs se donnent la main pour se déplacer ensemble ; imposer le dribble avec la main faible ; varier la largeur de la zone de passage.'),
  (8, 'Le roi du dribble', ARRAY['Protection','Duel'], ARRAY['Tête levée','Dribbler sans regarder','Protéger son ballon','Attaquer le ballon'], 'Le terrain est divisé en trois zones : les deux raquettes (zones 1 et 3) et le cercle central (zone 2). Tous les joueurs commencent dans la zone 2 avec un ballon. Le but est de conserver le contrôle de son ballon tout en essayant de pousser celui des autres joueurs hors de la zone dans laquelle ils se trouvent. Les joueurs doivent toujours dribbler. Lorsqu''un joueur fait sortir le ballon d''un adversaire sans perdre le sien, il monte dans la zone supérieure. En revanche, si son propre ballon sort de la zone, il descend dans la zone inférieure. Lorsqu''il n''est plus possible de monter ou de descendre, le joueur reste dans sa zone. L''objectif est de terminer la partie dans la zone la plus élevée.', 'Après chaque montée ou descente, réaliser un exercice ; imposer le dribble avec la main faible ; modifier la taille des zones.'),
  (9, 'Le jeu des cônes', ARRAY['Lecture','Vitesse'], ARRAY['Lecture du jeu','Tête levée','Dribbler vite','Dribbler sans regarder'], 'Quatre joueurs commencent dans une zone délimitée par des tacos avec un ballon chacun. 5 ou 7 cônes sont placés au centre. La première manche peut être réalisée sans ballon, puis avec ballon. Les joueurs prennent d''abord tous les cônes du centre. Ensuite, ils peuvent voler ceux des autres joueurs. Le premier qui obtient trois cônes sur son taco gagne.', 'Modifier le nombre de cônes ; modifier le nombre de joueurs ; imposer le dribble avec la main faible ; première manche sans ballon.'),
  (10, 'Les pirates', ARRAY['Attaque','Défense'], ARRAY['Changement vitesse','Tête levée','Dribbler sans regarder','Double dribble'], 'Deux équipes s''affrontent. Un large couloir central est délimité par des cônes et constitue la seule zone de passage entre les deux camps. Derrière chaque équipe se trouve un coffre contenant plusieurs trésors.

Avant le début de la manche, chaque équipe désigne ses attaquants et ses défenseurs. Tous les joueurs dribblent en permanence.

Les attaquants traversent le couloir central pour aller voler un trésor dans le coffre adverse. S''ils parviennent à prendre un trésor sans être touchés, ils doivent revenir dans leur camp en empruntant l''un des couloirs latéraux et déposer le trésor dans leur coffre.

Si un attaquant est touché avant d''avoir pris un trésor, il quitte immédiatement le terrain par un couloir latéral, retourne à son point de départ et recommence une nouvelle tentative.

À la fin du temps imparti, l''équipe ayant rapporté le plus de trésors remporte la manche. Les rôles sont ensuite inversés afin que tous les joueurs puissent attaquer et défendre.', 'Modifier la répartition attaquants/défenseurs ; modifier le nombre de trésors ; remplacer le double dribble par un exercice de coordination ou un tir.'),
  (11, 'Les chaises musicales', ARRAY['Musique','Réaction'], ARRAY['Dribbler vite','Lecture du jeu','Tête levée'], 'Les joueurs dribblent librement autour des anneaux pendant que la musique joue. Au départ, il y a autant d''anneaux que de joueurs. Quand la musique s''arrête, chacun doit trouver rapidement un anneau et s''y placer en gardant le contrôle du ballon. À chaque manche, on retire un anneau pour créer un défi de lecture et de vitesse.', 'Retirer plusieurs anneaux ; imposer la main faible ; demander un changement de main avant d''entrer ; varier la musique ou la durée des manches ; remplacer l''élimination par un atelier technique chronométré.'),
  (12, 'Slalom', ARRAY['Slalom','Relais'], ARRAY['Poteaux','Changement de direction','Dribble en vitesse'], 'Deux ou trois équipes s''affrontent, selon le nombre de joueurs. Des cônes ou des poteaux sont placés sur le terrain pour former deux couloirs parallèles, avec des repères de même couleur dans chaque couloir. Le premier joueur de chaque équipe démarre à une extrémité du terrain. Au signal, il réalise le slalom en passant toujours à l''extérieur des plots. À chaque changement de direction, il change de main afin de dribbler du bon côté et protéger le ballon. Lorsqu''il atteint l''autre extrémité, le joueur suivant de son équipe part immédiatement. L''équipe dont tous les joueurs ont terminé le parcours en premier remporte la manche.', 'Imposer le changement de main classique ; imposer le changement entre les jambes ; imposer le changement dans le dos. aller/retour'),
  (13, 'La course des cônes', ARRAY['Dribble bas','Coordination'], ARRAY['Dribbler bas','Deux actions simultanées'], 'Les joueurs travaillent par équipes de deux. Devant chaque équipe, quatre ou cinq cônes sont alignés et se touchent. Tout en dribblant bas, le premier joueur prend le dernier cône de la file et le dépose devant le premier, puis avance jusqu''au nouveau dernier cône pour recommencer. Il répète cette action jusqu''à franchir la ligne d''arrivée. Les cônes doivent toujours rester en contact les uns avec les autres : il est interdit de les espacer ou de les lancer pour aller plus vite. La première équipe qui atteint la ligne d''arrivée remporte la manche.', 'Changer de main à chaque aller-retour ; imposer l''utilisation de la main faible ; modifier le nombre de cônes.'),
  (14, 'La chenille', ARRAY['Échauffement','Coopération'], ARRAY['Mise en mouvement','Échauffement général'], 'Deux équipes. Au départ, un joueur de la première équipe lance un ballon en mousse le plus loin possible. Dès que le ballon est lancé, tous les joueurs de son équipe partent réaliser un parcours de mise en route autour du terrain.

Pendant ce temps, l''autre équipe va récupérer le ballon et forme une chenille : les joueurs se placent en file indienne et se font des passes de main en main du premier au dernier joueur, sans que le ballon ne quitte la file. Lorsque le ballon arrive au dernier joueur, celui-ci court se placer en tête de la chenille avec le ballon, tandis que les autres avancent d''une place. L''opération est répétée jusqu''à ce que la chenille atteigne la ligne d''arrivée ou un repère défini par l''entraîneur.

Les équipes échangent ensuite les rôles', 'Faire deux passages de chenille ; complexifier le parcours d''échauffement ; imposer un mode de déplacement différent ; changer le rôle des équipes à chaque manche.'),
  (15, 'Le garage', ARRAY[]::text[], ARRAY['Fondamentaux techniques','Diversité technique','Coordination','Lecture du jeu'], 'Toute la salle est transformée en un garage (voir schéma 5). Les joueurs circulent d''abord dans le rond-point central en dribblant avec une seule main. Ils choisissent ensuite l''une des quatre routes menant vers un atelier. Chaque atelier propose une tâche différente : retourner des cônes en dribblant, déplacer une balle avec la main libre, réaliser un geste de tir, effectuer une finition près du panier, jouer un 1 contre 1 ou encore réaliser un parcours de coordination suivi d''un tir. Une fois l''exercice terminé, les joueurs reviennent au rond-point par les voies de retour aménagées le long du terrain avant de repartir vers un nouvel atelier.', 'Ajouter de nouveaux ateliers ; prévoir une zone de repos (« station-service ») ; confier à certains joueurs le rôle de policiers pour orienter la circulation ; utiliser un banc retourné pour un exercice d''équilibre avant le tir ; modifier régulièrement les ateliers.'),
  (16, 'Passe et enchaînement', ARRAY[]::text[], ARRAY['Demander le ballon','Se démarquer','Tir en course','Éviter collisions'], 'Les joueurs se déplacent librement sur le terrain, ballon en main, tandis que les entraîneurs circulent également. Lorsqu''un joueur établit un contact visuel avec un entraîneur, il appelle le ballon, effectue une passe puis se démarque immédiatement pour recevoir le retour de passe. Dès la réception, il attaque le panier de son choix en dribblant si nécessaire, tout en gardant la tête levée afin d''éviter les collisions avec les autres joueurs qui réalisent le même exercice. L''action se termine par un tir, puis le joueur repart chercher un autre entraîneur.', 'Supprimer la passe et utiliser des plots de différentes couleurs comme signaux. Chaque couleur correspond à une action définie auparavant : attaquer un panier, rejoindre une ligne de la même couleur, échanger son ballon avec un partenaire, s''asseoir en dribblant ou toute autre consigne choisie par l''entraîneur.'),
  (17, 'Les oeufs dans le poulailler', ARRAY[]::text[], ARRAY['Technique de tir','Tir sous pression','Esprit d''équipe'], 'Former deux ou quatre équipes selon le nombre de joueurs. Chaque équipe se place à un point de départ défini, par exemple au centre du terrain, avec un seul ballon. Sous chaque panier sont disposés plusieurs cônes représentant les " oeufs ". À tour de rôle, les joueurs dribblent jusqu''au panier, effectuent un tir et récupèrent leur rebond. Si le tir est réussi, ils prennent un seul " oeuf " sous le panier. Ils reviennent ensuite en dribblant jusqu''à leur équipe, déposent l''oeuf dans leur nid (au point de départ), transmettent le ballon au joueur suivant et se replacent à la fin de la file. Si le tir est manqué, le joueur récupère son rebond, revient sans oeuf et passe le ballon au coéquipier suivant. La première équipe qui rapporte tous les oeufs dans son nid remporte la partie.', 'Ajouter des plots ou des obstacles à franchir avant le tir ; intégrer un passeur qui reçoit puis remet le ballon avant la finition ; voir schéma 1 : après la passe, le passeur récupère le rebond, ramène le ballon au point de départ et devient le joueur suivant ; modifier le nombre d''oeufs ou la distance de tir selon le niveau du groupe.'),
  (18, 'Les numéros', ARRAY['Réaction','Pression'], ARRAY['Technique de tir','Tir sous pression','Vitesse d''exécution','Concentration'], 'Former deux ou quatre équipes de même effectif. Chaque joueur reçoit un numéro et toutes les équipes se placent au centre du terrain, face au panier qu''elles doivent attaquer. Lorsque l''entraîneur annonce un numéro, les joueurs correspondants démarrent immédiatement en dribblant vers leur panier. Ils doivent contrôler leur vitesse, réaliser leur attaque et marquer le plus rapidement possible. Le premier joueur à inscrire son panier remporte le duel et marque un point pour son équipe. Les joueurs reviennent ensuite au centre et un nouveau numéro est appelé.', 'Éliminer ou non le joueur qui perd le duel ; imposer différents types de finition ; commencer avec le ballon en main ou aller le récupérer avant de partir ; modifier la distance ou le point de départ selon le niveau du groupe.'),
  (19, 'Éliminatoire', ARRAY['Duel','Vitesse'], ARRAY['Tir sous pression','Dribble en vitesse','Concentration','Rapidité d''exécution'], 'Former deux équipes placées chacune dans un coin de la ligne de fond. Un joueur de chaque équipe se place au départ avec un ballon. Au signal de l''entraîneur, les deux joueurs partent simultanément. Des cônes placés au centre du terrain créent deux couloirs distincts qu''il est interdit de quitter. Chaque joueur doit rejoindre le panier opposé, marquer un panier, récupérer son rebond, revenir vers son panier de départ, marquer une deuxième fois puis terminer le parcours.', 'Donner deux vies à chaque joueur avant son élimination ; définir un petit défi ou un gage pour le joueur ou l''équipe éliminée ; modifier la distance de tir ou imposer un type de finition particulier selon le niveau du groupe.'),
  (20, 'À la pêche aux poissons', ARRAY['Technique','Mains'], ARRAY['Placement des mains','Doigts vers le haut, doigts vers le bas','Coordination du geste','Finition du tir'], 'Chaque joueur dispose d''un ballon et travaille en position statique face au panier. L''exercice débute par une démonstration des principaux éléments de la technique de tir. Le ballon repose sur la main forte, les doigts sont écartés et un espace est conservé entre la paume et le ballon. La main faible guide uniquement le ballon sans le pousser. Au moment de l''extension, les doigts sont orientés vers le haut afin d''accompagner le ballon, puis terminent vers le bas lors du relâchement.Chaque joueur dispose d''un ballon et se place face au panier. L''exercice débute par une démonstration de la technique de tir. Le ballon est posé sur la main forte, les doigts sont écartés et la paume ne touche pas complètement le ballon afin d''assurer un meilleur contrôle. La main faible est placée sur le côté et sert uniquement de guide. Les joueurs réalisent ensuite le geste lentement : le ballon monte devant le visage, les jambes s''étendent, puis le bras de tir se tend complètement. Au moment du lâcher, le poignet casse vers l''avant et les doigts terminent orientés vers le sol, comme s''ils allaient " attraper un poisson " dans le panier. L''objectif est de reproduire un geste fluide, équilibré et identique à chaque répétition.', 'Travailler par deux : chaque joueur lance le ballon verticalement en reproduisant le geste complet, puis tente de le récupérer dans la même main sans se déplacer ; varier la distance de tir ou utiliser une seule main.'),
  (21, 'Le cinq de base', ARRAY['Technique','Ateliers'], ARRAY['Coordination du tir','Placement des mains','Finition du geste','Précision du tir'], 'Former quatre équipes, chacune sur un panier latéral. Devant chaque panier, placer cinq plots retournés, chacun portant un ballon (voir schéma 1). Les cinq positions de tir sont réparties autour du panier. Au signal, le premier joueur de chaque équipe court depuis le milieu de terrain vers une position encore occupée par un ballon, réalise son tir en privilégiant la qualité du geste plutôt que la vitesse, puis récupère le rebond.', 'Ajouter des obstacles avant d''atteindre la position de tir ; imposer une finition de la main droite ou de la main gauche ; éloigner progressivement certaines positions de tir ; adapter les distances selon le niveau du groupe.'),
  (22, 'La cage qui rétrécit', ARRAY['Protection de balle','Perception'], ARRAY['Protection sous pression','Tête levée'], 'Tous les joueurs dribblent librement dans un espace délimité (par exemple le rond central puis, au signal, la zone réservée). Chacun doit à la fois essayer de faire perdre le dribble d''un camarade d''un simple contact sur le ballon, et protéger le sien. Un joueur qui perd le contrôle de son ballon ou qui sort de l''espace délimité est éliminé. Le dernier joueur restant avec son ballon a gagné. L''entraîneur réduit progressivement l''espace de jeu au fur et à mesure que le nombre de joueurs diminue, pour maintenir la difficulté.', 'Ajouter des cerceaux au sol qui délimitent des zones interdites pour augmenter l''incertitude. Imposer une seule main de dribble à tout le monde. Retirer un joueur éliminé mais le faire revenir après 30 secondes de pompes.'),
  (23, 'Le premier pas gagnant', ARRAY['Premier pas','Appuis'], ARRAY['Départ direct','Départ croisé','Créer un écart'], 'Un ballon par joueur, 6 plots disposés en éventail face au panier. Chaque joueur, à tour de rôle, part d''un plot et exécute un départ en dribble vers le panier : une série de 3 départs directs (le pied du côté de la main de dribble part en premier), puis une série de 3 départs croisés (le pied opposé part en premier). Après avoir tourné sur les 3 positions, les joueurs changent de main de dribble et recommencent.', 'Ajouter un plot juste devant le joueur pour matérialiser un défenseur à éviter. Remplacer le plot par un défenseur statique, puis par un défenseur qui peut gêner légèrement.'),
  (24, 'Le combo 4 changements', ARRAY['Changement de main'], ARRAY['4 changements de main','Fluidité'], 'Les joueurs traversent la largeur du terrain par vagues. Sur la première moitié, ils dribblent en enchaînant des changements de main simples à chaque plot. Sur la deuxième moitié, ils utilisent le changement de main dans le dos ou avec renversement. On peut terminer chaque traversée par un tir en course pour donner un objectif concret à l''exercice.', 'Imposer un seul type de changement de main pour tout le groupe afin de bien l''automatiser avant de mélanger. Ajouter un temps chronométré pour créer un peu de compétition amicale entre les joueurs.'),
  (25, 'Une passe de plus', ARRAY['Partage du ballon','Circulation de balle'], ARRAY['Circulation rapide','Tir ouvert'], 'Trois ou quatre joueurs se placent aux positions extérieures habituelles. Un joueur (ou l''entraîneur) fait une première passe. Dès que le receveur a le ballon, le joueur suivant crie « une de plus ! » pour signaler qu''il est démarqué, et reçoit immédiatement la passe. Le troisième joueur fait la même chose, et tire après cette dernière passe. L''exercice tourne ensuite en changeant de point de départ.', 'Ajouter un dribble avant le tir pour le receveur final. Introduire un défenseur passif qui ferme une ligne de passe pour forcer une lecture réelle.'),
  (26, 'L''étoile filante', ARRAY['Passe en mouvement','Vitesse'], ARRAY['Passe en vitesse','Alignement des couloirs'], 'Cinq colonnes de joueurs se répartissent en éventail sur toute la largeur du terrain. La balle circule d''une colonne à l''autre selon un ordre fixe pendant que tous les joueurs avancent en sprint vers le panier adverse. Chaque passeur suit sa passe pour rejoindre la colonne suivante. L''exercice se termine par un tir en course du dernier receveur.', 'Changer l''ordre de circulation de la balle pour éviter que les joueurs anticipent trop. Chronométrer chaque traversée complète du terrain.'),
  (27, 'Les 10 passes d''or', ARRAY['Anti pertes de balle','Espacement'], ARRAY['Anti pertes de balle','Occuper l''espace'], 'En demi-terrain, deux équipes de 3 joueurs s''affrontent. L''équipe en attaque doit réaliser 10 passes consécutives sans marcher, sans double-dribble et sans perte de balle, sans même chercher à marquer. Les attaquants doivent passer, couper, dribbler, poser des écrans et bien s''espacer pour y parvenir. Si l''attaque réussit ses 10 passes, elle n''a pas à défendre au tour suivant ; sinon, on inverse les rôles.', 'Réduire à 7 passes pour les groupes plus jeunes. Autoriser un tir libre après les 10 passes réussies, comme récompense.'),
  (28, 'Reçois et frappe', ARRAY['Réception en mouvement','Triple menace'], ARRAY['Réception en mouvement','Triple menace'], 'Deux colonnes de joueurs se font face de part et d''autre du panier, l''une avec ballons. Le premier joueur de la colonne sans ballon part en un léger déplacement vers l''intérieur pour recevoir une passe courte du premier joueur de l''autre colonne, puis tire immédiatement. Chacun récupère son ballon ou rejoint la colonne opposée selon l''organisation choisie par l''entraîneur.', 'Allonger progressivement la distance de course avant la réception. Ajouter une feinte de tir avant de tirer réellement.'),
  (29, 'Le tour des 4 zones', ARRAY['Répétition','Variété de tirs'], ARRAY['Variété de tirs','Rythme soutenu'], 'Les joueurs travaillent par deux, un tireur et un rebondeur/passeur, sur un panier. À chaque emplacement autour de la ligne à 3 points, le tireur enchaîne : un tir à 3 points, un tir en suspension après feinte, un tir en catch-and-shoot, puis une entrée en lay-up. Le partenaire récupère et repasse à chaque fois. Après la série complète à un emplacement, les deux joueurs échangent les rôles, puis passent à l''emplacement suivant.', 'Réduire à 2 types de tir pour les plus jeunes. Ajouter un objectif de points (par exemple 3 pts par panier à 3 points réussi) pour créer une petite compétition entre binômes.'),
  (30, 'Attaque et ressors', ARRAY['Drive and kick','Lecture de la défense'], ARRAY['Drive and kick','Replacement rapide'], 'Le porteur de balle démarre à l''aile avec un ballon, pénètre en dribble vers la raquette comme s''il cherchait à marquer, puis ressort la balle vers un partenaire qui s''est replacé sur la ligne à 3 points. Après sa passe, le premier joueur sprinte se replacer à l''aile opposée pour être disponible à son tour. Le receveur doit lui-même se rendre disponible en glissant le long de l''arc ou en revenant vers le corner.', 'Ajouter un défenseur réel sur le porteur de balle pour rendre la lecture authentique. Enchaîner directement sur un 1 contre 1 si la passe de ressortie n''est pas possible.'),
  (31, 'Passe, démarque, duel', ARRAY['Démarquage','Duel'], ARRAY['Passe et démarquage','1 contre 1'], 'Trois joueurs par quart de terrain. Le porteur de balle fait la passe à l''ailier et va aussitôt le défendre. L''ailier fait la passe à un troisième joueur puis effectue un démarquage simple (en V) pour se recréer un appel de balle, pendant que son défenseur le suit. Dès qu''il reçoit à nouveau le ballon, il joue le 1 contre 1 face à ce défenseur. Les rôles tournent ensuite entre les trois joueurs.', 'Remplacer le démarquage en V par un démarquage en L ou en backdoor pour varier les trajectoires. Autoriser le passeur à choisir le moment de la passe pour développer la disponibilité permanente du receveur.'),
  (32, 'La tresse à trois', ARRAY['Transition','Surnombre'], ARRAY['Circulation en tresse','Décision en 2c1'], 'Trois joueurs remontent le terrain en tressant leurs déplacements : chacun passe le ballon puis suit sa passe en courant derrière le receveur pour se replacer sur le côté opposé. Le joueur qui effectue la troisième passe de la tresse devient alors défenseur, et les deux autres terminent l''action en situation de 2 contre 1 vers le panier.', 'Faire l''exercice sur tout le terrain aller-retour pour ajouter de la condition physique. Imposer un nombre maximum de dribbles pour forcer la prise de décision rapide en 2 contre 1.'),
  (33, 'La chaîne sans fin', ARRAY['Transition','Automatismes'], ARRAY['Automatismes de transition'], 'Trois colonnes de joueurs sous chaque panier, sans opposition dans un premier temps, pour bien installer les trajectoires et le timing des passes de la contre-attaque. Le porteur central lance le mouvement, les deux ailes courent en s''écartant vers les couloirs latéraux, la balle circule jusqu''à la finition au panier. Le groupe suivant part dès que le précédent a fini sa finition.', 'Ajouter un défenseur qui revient depuis la ligne de fond après un léger délai, pour passer progressivement à une contre-attaque avec opposition légère.'),
  (34, 'Ferme et bondis', ARRAY['Close-out','Appuis défensifs'], ARRAY['Close-out','Position basse'], 'Un joueur part depuis le milieu de la raquette et court fermer la distance (« close-out ») sur un partenaire placé à l''extérieur avec un ballon, en petits pas chassés et les mains hautes pour contester un tir éventuel sans sauter dans le tir. Dès qu''il est arrivé, il doit être capable de réagir si l''attaquant part en dribble d''un côté ou de l''autre. Les rôles s''inversent après chaque répétition.', 'Le partenaire attaquant peut choisir librement entre tirer, partir en dribble à droite ou à gauche, obligeant le défenseur à vraiment lire la situation plutôt qu''à anticiper.'),
  (35, 'Le relais réveil-matin', ARRAY['Mise en train','Ludique'], ARRAY['Échauffement dynamique'], 'Deux équipes en relais, chaque joueur dribble en slalom entre une série de plots avant de revenir toucher la main du suivant. On peut imposer une contrainte différente à chaque tour : main droite uniquement, main gauche uniquement, changement de main à chaque plot. L''équipe qui termine tous ses passages en premier gagne la manche.', 'Terminer chaque passage par un tir pour ajouter un objectif technique en plus de la vitesse. Réduire l''espacement des plots pour les groupes plus expérimentés.'),
  (36, 'Le voleur de foulards en dribble', ARRAY['Jeu','Protection de balle'], ARRAY['Protection de balle','Vigilance'], 'Chaque joueur dribble en permanence et place un petit foulard ou un chasuble dans l''arrière de son short. Au signal, tous les joueurs essaient de voler le plus de foulards possible aux autres, sans jamais arrêter leur propre dribble ni perdre leur foulard. Un joueur peut s''accorder une immunité temporaire une seule fois par manche en s''asseyant par terre tout en continuant de dribbler.', 'Réduire l''espace de jeu pour augmenter la densité et la difficulté. Compter les foulards volés par joueur pour désigner un vainqueur à la fin de chaque manche.'),
  (37, '1, 2, 3 Soleil en dribble', ARRAY['Jeu','Arrêts'], ARRAY['Arrêt net','Protection du ballon'], 'Un joueur sans ballon se place face à un mur (ou dos au groupe) et dit à voix haute « 1, 2, 3, Soleil ! » avant de se retourner. Pendant ce temps, tous les autres joueurs avancent en dribblant vers lui. Dès qu''il se retourne, tout le monde doit être totalement immobile, ballon compris (pas de rebond visible) : tout joueur surpris en mouvement retourne au point de départ. Le premier joueur à atteindre le meneur du jeu gagne et prend sa place pour la manche suivante.', 'Imposer une main de dribble différente selon les manches. Autoriser uniquement des petits pas chassés en plus du dribble pour travailler la coordination.'),
  (38, 'Le loup et les brebis', ARRAY['Jeu','Initiation'], ARRAY['Tête levée','Jeu simple'], 'Dans un espace délimité, chaque enfant dribble son propre ballon. Un enfant désigné est « le loup » et doit toucher une des « brebis » en restant lui-même en dribble. Dès qu''une brebis est touchée, elle devient loup à son tour et l''ancien loup redevient brebis. Pour les plus grands, on peut ajouter qu''un enfant qui perd son ballon, fait un double-dribble ou sort du terrain a le même sort qu''un enfant touché.', 'Désigner 2 loups en même temps pour accélérer le jeu avec un grand groupe. Réduire la taille de l''espace pour augmenter la difficulté à mesure que les enfants progressent.'),
  (39, 'Le puzzle du tireur', ARRAY['Jeu','Motivation'], ARRAY['Répétition du geste','Technique avant le score'], 'Deux équipes s''affrontent sur deux paniers. Plusieurs petits cônes marquent différents emplacements de tir, et une pièce de puzzle est cachée derrière chacun. Au signal, un joueur de chaque équipe dribble jusqu''à un cône, tire, et s''il marque ET que son geste technique est jugé correct par l''entraîneur, il peut ramener la pièce de puzzle et la placer sur le plateau de son équipe avant de repartir. En cas d''échec (panier manqué ou geste incorrect), le joueur revient sans pièce. La première équipe à compléter son puzzle gagne.', 'Adapter la difficulté des positions de tir selon le niveau. Faire juger le geste par les autres enfants à tour de rôle, pour les responsabiliser.'),
  (40, 'La chasse à l''arc-en-ciel', ARRAY['Jeu','Réactivité'], ARRAY['Passe rapide en équipe','Repères visuels'], 'Disperser dans la salle des formes de couleurs différentes (ronds, carrés, triangles en plusieurs couleurs). Former des équipes de 2 joueurs avec un ballon chacune. L''entraîneur annonce une forme et une couleur (par exemple « rond jaune »). La première équipe qui amène son ballon sur la forme et la couleur annoncées, en respectant les consignes techniques données (passes correctes, pas de dribble illégal, etc.), marque un point.', 'Complexifier en annonçant une suite de plusieurs formes à atteindre dans l''ordre. Imposer un type de passe précis (passe à 2 mains, passe à terre) selon la forme annoncée.'),
  (41, 'Le parcours du champion', ARRAY['Coordination','Parcours'], ARRAY['Enchaînement technique','Coordination'], 'Un parcours complet en dribble : slalom entre des plots, puis au centre du terrain toucher au sol deux repères (main droite puis main gauche) sans arrêter le dribble, un nouveau slalom, un tir depuis un petit cône, récupération du rebond, une séquence de dribble bas puis à hauteur de hanche jusqu''à un grand cône, un tour complet autour de cerceaux disposés au sol, puis un nouveau slalom et un dernier tir avant de reprendre le parcours depuis le début.', 'Transformer en jeu de cartes : à chaque panier réussi, l''enfant peut prendre une carte à jouer et la garder sur lui ; celui qui en a le plus à la fin du temps imparti gagne.'),
  (42, '45 secondes de tir sous pression', ARRAY['Pression du temps','Compétition'], ARRAY['Efficacité sous pression','Vitesse d''exécution'], 'Un joueur enchaîne des tirs le plus vite possible depuis les positions choisies par l''entraîneur. Chaque tir manqué retire un point, chaque tir marqué en ajoute un. L''exercice se termine dès que le joueur atteint 11 points (que ce soit en ayant marqué beaucoup ou raté beaucoup), ce qui crée une vraie pression de rattrapage en cas de séquence de tirs manqués.', 'En faire un défi entre deux joueurs sur deux paniers voisins, le premier à 11 points gagne. Imposer un déplacement (course latérale, sprint) entre chaque tir pour ajouter de la fatigue.'),
  (43, 'Le duel jusqu''à 10', ARRAY['Rebond offensif','Coopération'], ARRAY['Rebond offensif','Motivation'], 'Deux joueurs, un tireur et un rebondeur, cumulent leurs points ensemble jusqu''à atteindre 10 : chaque panier du tireur vaut un point, et chaque rebond offensif transformé en panier par le rebondeur avant que le ballon ne touche le sol vaut également un point pour l''équipe. Les deux joueurs échangent ensuite les rôles.', 'Faire une compétition entre deux binômes sur deux paniers, le premier binôme à 10 gagne. Imposer au rebondeur de terminer uniquement en une main pour travailler la finition rapide.'),
  (44, 'Mon tir, mes règles', ARRAY['Autonomie offensive','Lecture de la défense'], ARRAY['Autonomie offensive','Peu de dribbles'], 'Le joueur reçoit le ballon depuis différentes positions (aile, milieu, poste moyen) face à un défenseur, et doit chercher à tirer en utilisant le moins de dribbles possible, sans chercher la pénétration complète vers le cercle. Si la situation ne permet pas de tirer, il passe la balle à l''entraîneur ou à un partenaire et continue à jouer sans ballon pour se replacer et redemander.', 'Limiter explicitement à 1 ou 2 dribbles maximum pour forcer la prise de décision rapide. Ajouter un défenseur passif puis progressivement plus actif selon le niveau du joueur.'),
  (45, 'Tir dans la bousculade', ARRAY['Contact','Concentration'], ARRAY['Tir sous contact','Concentration'], 'Le tireur s''auto-passe le ballon, prend un dribble puis s''arrête pour tirer, pendant qu''un ou deux défenseurs tentent de gêner le tir en poussant un gros coussin ou un tapis souple contre lui (jamais un contact direct dangereux). On commence avec un seul coussin placé devant, puis derrière, puis les deux en même temps pour habituer progressivement le joueur à tirer en gardant son équilibre et sa concentration sur le cercle malgré la gêne.', 'N''utiliser qu''un seul niveau de difficulté à la fois avant de cumuler. Insister sur la protection du ballon après le dribble avec le bras libre avant chaque tir.'),
  (46, 'L''escalier du surnombre', ARRAY['Progression pédagogique','Surnombre'], ARRAY['Surnombre progressif','Lecture collective'], 'Cette séance suit une progression par étapes, en ne passant à l''étape suivante que lorsque le groupe maîtrise la précédente : d''abord un simple 2 contre 1, puis un 2 contre 1 avec un joueur supplémentaire qui rejoint l''action après coup, puis un 2 contre 2, et enfin un 3 contre 2. Chaque étape reprend les mêmes principes de base (trouver l''espace libre, faire la bonne passe au bon moment) avec un niveau d''opposition croissant.', 'Adapter le temps passé sur chaque étape selon la vitesse de progression du groupe observée par l''entraîneur. Terminer la séance par un 3 contre 3 comme forme de jeu aboutie pour les plus expérimentés.'),
  (47, 'L''étoile défensive', ARRAY['Communication','Positionnement'], ARRAY['Positions défensives','Communication'], 'Quatre attaquants se répartissent autour de la ligne à 3 points (deux dans le prolongement de la ligne de lancers francs, deux aux ailes). La balle circule d''un attaquant à l''autre pendant que les défenseurs ajustent leur position à chaque passe : celui à une passe du ballon reste en position de refus avec une main dans la ligne de passe ; celui à deux passes du ballon recule en aide au tiers du chemin ; celui à trois passes recule en aide à mi-chemin. Chaque joueur doit annoncer sa position à voix haute (« Ballon ! », « Refus ! », « Aide ! ») à chaque passe. Au début, on demande à l''attaque d''attendre le signal de l''entraîneur avant chaque passe pour bien vérifier les positions ; une fois les automatismes acquis, l''exercice devient dynamique avec un maximum de 3 dribbles autorisés pour l''attaque.', 'Passer en version « live » avec opposition réelle une fois les positions bien comprises. Retirer la limite de dribbles pour les groupes plus expérimentés.'),
  (48, 'Le renfort qui arrive', ARRAY['Transition','Surnombre'], ARRAY['Avantage numérique','Vitesse de décision'], 'Deux équipes se placent sur les côtés au milieu de terrain, avec un défenseur de chaque équipe déjà positionné à son panier respectif. Deux attaquants partent avec un ballon juste après la ligne médiane et attaquent le premier défenseur en 2 contre 1, en essayant de le faire s''engager sur l''un des deux. Dès que les attaquants franchissent la ligne médiane, un deuxième défenseur sprinte depuis le rond central pour rejoindre son coéquipier, transformant la situation en 2 contre 2 avant la fin de l''action.', 'Limiter le nombre de dribbles autorisés pour forcer une décision rapide. Faire tourner les rôles pour que chaque joueur passe par les 4 positions (les deux attaquants et les deux défenseurs).'),
  (49, 'Rebond, cours, recommence', ARRAY['Rebond défensif','Transition'], ARRAY['Rebond puis transition','Sans temps mort'], 'Deux attaquants avec ballon partent depuis la ligne médiane contre deux défenseurs déjà en place. Après le tir, les deux défenseurs doivent boxer-out et se disputer le rebond avec les attaquants. Une fois l''action terminée (panier marqué ou rebond capté), les attaquants quittent le terrain et une nouvelle paire de défenseurs entre en jeu : l''ancienne paire de défenseurs devient la nouvelle paire d''attaquants pour l''action suivante. L''exercice tourne ainsi en continu, chaque paire alternant entre attaque et défense.', 'Passer à un format 3 contre 2 pour donner un avantage numérique clair à l''attaque et se concentrer sur la lecture du surnombre. Comptabiliser les points marqués par chaque binôme sur plusieurs passages pour ajouter un enjeu.'),
  (50, 'Pivote et échappe-toi', ARRAY['Triple menace','Protection'], ARRAY['Triple menace','Pivot d''échappement'], 'Face à un défenseur, l''attaquant reçoit le ballon en triple menace et doit le protéger avec des pivots et des mouvements de « rip » (ballon ramené vivement d''un genou à l''épaule opposée) sans avoir le droit de dribbler pendant 4 à 5 secondes. Au signal, l''attaquant utilise l''un de ses pivots pour créer un espace par rapport au défenseur et part en dribble vers le panier pour terminer l''action.', 'Faire varier le temps de protection avant le signal de départ. Autoriser le défenseur à mettre une pression croissante au fil des répétitions.'),
  (51, 'Passe et va', ARRAY['Passe et course','Automatismes'], ARRAY['Passe et course','Réflexe de coupe'], 'Deux joueurs partent du milieu de terrain, l''un avec ballon. Le porteur passe à son partenaire puis sprinte aussitôt vers le panier en coupant devant lui (« passe-et-va »). Le partenaire, dès qu''il voit le coureur démarrer, lui repasse le ballon pour qu''il termine en lay-up. Les rôles s''inversent à chaque passage dans la file d''attente.', 'Ajouter un défenseur passif sur le coureur pour introduire une légère opposition. Faire l''exercice sur tout le terrain pour y ajouter de la vitesse et de la condition physique.'),
  (52, 'Le jeu du « Coach a dit »', ARRAY['Attention','Écoute'], ARRAY['Écoute','Réactivité'], 'Comme le jeu « Jacques a dit », les joueurs n''exécutent une consigne de l''entraîneur (sauter sur un pied, toucher le sol, courir sur place, etc.) que si elle est précédée de « Coach a dit ». Si un joueur réagit à une consigne qui n''était pas précédée de cette formule, il doit s''asseoir et attendre la fin de la manche. Le dernier joueur encore debout gagne cette manche.', 'Remplacer les actions générales par des gestes techniques de basket (dribbler, pivoter, tir imaginaire) pour combiner échauffement ludique et rappel technique. Faire des manches courtes et répétées pour garder tout le monde impliqué.'),
  (53, 'La course-poursuite défensive', ARRAY['Transition défensive','Repli'], ARRAY['Repli défensif','Gestion de l''espace'], 'Un attaquant part en dribble depuis le milieu de terrain pendant qu''un défenseur, initialement en retard, doit sprinter pour se replacer devant lui. Le défenseur ne doit pas chercher à prendre directement le ballon mais à ralentir la progression de l''attaquant, à évaluer la direction de son déplacement, et à occuper un maximum d''espace avec ses bras une fois replacé face à lui.', 'Faire varier le point de départ du défenseur pour simuler différents degrés de retard. Enchaîner directement sur un 1 contre 1 complet une fois le défenseur replacé.'),
  (54, 'Le cri d''alerte', ARRAY['Communication défensive','Trois-quarts terrain'], ARRAY['Communication défensive','Feinte'], 'Sur les trois quarts du terrain, deux attaquants partent en contre-attaque contre un seul défenseur, avec un deuxième défenseur qui doit rejoindre l''action après un léger délai. Le défenseur seul doit communiquer, feinter une intervention sur le porteur pour le ralentir, sans jamais se faire déborder complètement avant l''arrivée de son coéquipier.', 'Faire l''exercice en aller-retour, sans remise en jeu, pour enchaîner directement plusieurs répétitions. Interdire explicitement les fautes antisportives pour que les défenseurs apprennent les bonnes solutions plutôt qu''une faute systématique.'),
  (55, 'Franchir le mur', ARRAY['Écrans','Défense individuelle'], ARRAY['Franchir un écran','Contact avec l''attaquant'], 'Un attaquant utilise un écran posé par un partenaire pour se démarquer, pendant qu''un seul défenseur doit le suivre à travers l''écran (le poseur d''écran n''est pas défendu dans cette version simplifiée). Le défenseur doit maintenir un contact avant-bras/hanche avec son attaquant, se créer un espace suffisant pour passer entre l''attaquant et le poseur d''écran, et franchir l''écran en même temps que lui plutôt que de le contourner largement.', 'Ajouter un deuxième défenseur sur le poseur d''écran une fois le mouvement individuel maîtrisé, pour introduire une vraie collaboration défensive à 2. Varier le type d''écran (de face, croisé, vers l''intérieur) pour multiplier les trajectoires à défendre.'),
  (99, 'Viejo', ARRAY[]::text[], ARRAY[]::text[], '', '')
    ) as t(number, name, tags, objectives, description, variants)
  loop
    select id, categories, material, age, translation_group_id, visibility, favorite, difficulty
      into en_row
      from public.exercises
      where organization_id = '00000000-0000-0000-0000-000000000001' and number = fr.number and language = 'en'
      limit 1;

    if en_row.id is null then
      raise notice 'Pas de version anglaise trouvée pour le numéro %, ignoré.', fr.number;
      continue;
    end if;

    -- Déjà traduit ? On ne duplique pas si on relance ce script.
    if exists (
      select 1 from public.exercises
      where translation_group_id = en_row.translation_group_id and language = 'fr'
    ) then
      continue;
    end if;

    insert into public.exercises
      (organization_id, number, name, favorite, difficulty, age, categories, material,
       tags, objectives, description, variants, visibility, language, translation_group_id)
    values
      ('00000000-0000-0000-0000-000000000001', fr.number, fr.name, en_row.favorite, en_row.difficulty, en_row.age,
       en_row.categories, en_row.material, fr.tags, fr.objectives, fr.description, fr.variants,
       en_row.visibility, 'fr', en_row.translation_group_id);
  end loop;
end $$;
